# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_auto_20190119_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
