# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_auto_20190119_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='waittime',
            field=models.IntegerField(null=True),
        ),
    ]
