# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0008_appointment_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='complete_time',
            new_name='session_complete_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='session_start_time',
        ),
    ]
